---
title: "Modelo"
author: "Equipo 1"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(bnlearn)
```

```{r}
data <- read.csv("../data_util/ensanut2022_muestras_selected.csv")
head(data)
```

```{r}
data = data |>
        select(-FOLIO_INT, -Entidad, -Municipio)
data
```

DAG 1 (metabólico + lípidos con exposición a PM y NOx)

```{r}
dag1 <- model2network("[PM_2_5][NOx][valor_PCR|PM_2_5:NOx][valor_INSULINA|valor_PCR][valor_GLU_SUERO|valor_INSULINA][valor_COL_LDL|PM_2_5:NOx:valor_PCR][valor_TRIG|PM_2_5:NOx:valor_PCR][valor_COL_HDL|PM_2_5:NOx:valor_PCR][valor_COLEST|valor_COL_LDL:valor_TRIG:valor_COL_HDL][valor_CREAT|valor_PCR:valor_COLEST:valor_TRIG:valor_COL_HDL][hb02|valor_PCR:valor_CREAT:PM_2_5:NOx]")
```

DAG 2 (contaminantes criterio → inflamación → metabolismo y lípidos)

```{r}
dag2 <- model2network("[SO_2][CO][NOx][COV][PM_010][PM_2_5][NH_3][valor_PCR|SO_2:NOx:PM_010:PM_2_5:NH_3][valor_INSULINA|valor_PCR:PM_2_5:NOx][valor_GLU_SUERO|valor_INSULINA][valor_COL_LDL|valor_PCR:PM_2_5:NOx][valor_TRIG|valor_PCR:PM_2_5:NOx:CO][valor_COL_HDL|valor_PCR:PM_2_5:NOx][valor_COLEST|valor_COL_LDL:valor_TRIG:valor_COL_HDL][valor_CREAT|valor_PCR:valor_COLEST:valor_TRIG:valor_COL_HDL:PM_2_5:NOx][hb02|valor_PCR:CO]")
```

DAG 3 (“contaminantes” explicitados → inflamación → metabolismo + lípidos + función renal)

```{r}
dag3 <- model2network("[SO_2][CO][NOx][COV][PM_010][PM_2_5][NH_3][valor_GLU_SUERO][valor_PCR|SO_2:CO:NOx:COV:PM_010:PM_2_5:NH_3][valor_INSULINA|valor_PCR][valor_GLU_SUERO|valor_INSULINA][valor_COL_LDL|valor_PCR][valor_TRIG|valor_PCR][valor_COL_HDL|valor_PCR][valor_COLEST|valor_COL_LDL:valor_TRIG:valor_COL_HDL][valor_CREAT|valor_PCR]")
```

```{r}
graphviz.plot(dag1, shape = "ellipse")
```

```{r}
graphviz.plot(dag2, shape = "ellipse")
```

```{r}
graphviz.plot(dag3, shape = "ellipse")
```
